name: NoMachine Windows

on:
  workflow_dispatch:

jobs:
  nomachine:
    runs-on: windows-latest
    steps:
      - name: Install & Connect Tailscale
        shell: powershell
        run: |
          $tsUrl = "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi"
          $installerPath = "$env:TEMP\tailscale.msi"
          Invoke-WebRequest -Uri $tsUrl -OutFile $installerPath
          Start-Process msiexec.exe -ArgumentList "/i", "`"$installerPath`"", "/quiet", "/norestart" -Wait
          & "$env:ProgramFiles\Tailscale\tailscale.exe" up --authkey=${{ secrets.TAILSCALE_AUTHKEY }} --hostname=gh-runner-${{ github.run_id }}
          $tsIP = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
          "TAILSCALE_IP=$tsIP" | Out-File -Append $env:GITHUB_ENV

      - name: Open NoMachine Firewall Port
        shell: powershell
        run: |
          netsh advfirewall firewall add rule name="NoMachine" dir=in action=allow protocol=TCP localport=4000

      - name: Download, Install & Start NoMachine
        shell: powershell
        run: |
          & "C:\Windows\System32\curl.exe" -o nomachine.exe https://web9001.nomachine.com/download/9.3/Windows/nomachine_9.3.7_1_x64.exe
          Start-Process -FilePath .\nomachine.exe -ArgumentList "/S" -Wait
          sc start nxserver

      - name: Show Connection Details & Keep Alive
        shell: powershell
        run: |
          Write-Host "Thanks to MR.English2008 for this perfect work"
          Write-Host "follow for more in my telegram channel"
          Write-Host "https://t.me/ME2008_RDP"
          Write-Host "======================="
          Write-Host "CONNECTION DETAILS:"
          Write-Host "nomachine IP: $($env:TAILSCALE_IP):4000"
          while ($true) {
            Start-Sleep -Seconds 300
          }
